---
baseurl: "http://simplaio.github.io/rucksack"
languageCode: "en-gb"
title: "Rucksack | CSS Superpowers"
contentdir: "docs"
dataDir: "src/data"
staticdir: "src/static"

params:
  description: "Rucksack ia a little bag of CSS superpowers, built on PostCSS"
  author: "Simpla"
---
